# Generated by Django 4.2 on 2023-10-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pimg', models.ImageField(upload_to='images/')),
                ('pprice', models.IntegerField(max_length=20)),
                ('pdiscount', models.IntegerField(max_length=20)),
                ('pdelivary_fee', models.IntegerField(max_length=20)),
                ('pcategary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat')),
            ],
        ),
    ]
