# Generated by Django 4.2 on 2023-10-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=20)),
                ('user', models.IntegerField(max_length=20)),
                ('pname', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
