# Generated by Django 4.2 on 2023-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='addaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=240)),
            ],
        ),
    ]
